### ISSUE TITLE
Support for Local Push State Information

### ISSUE THREAD

**Issue by shbatm** [prystupa/bond-api#3]
Hello! Just started using the Bond integration for Home Assistant, awesome work and thank you!

I was looking through their API documentation and the integration and was wondering if you had any plans to add support for their beta "BPUP" UDP Socket to be able to get faster state change updates in Home Assistant (change from Local Pull to Local Push and get rid of polling)?

http://docs-local.appbond.com/#section/Bond-Push-UDP-Protocol-(BPUP)

**Comment by bdraco** [comment]
It looks like HomeSeer has it working in production

http://plugins.homeseer.com/releasenotes?productid=372
